### ISSUE TITLE
Remove miniserde dependency

### ISSUE THREAD

**Issue by dtolnay** [eupn/miniserde-derive-enum#1]
https://github.com/eupn/miniserde-derive-enum/blob/91722a509d048b29da18903b26fffbfff6936e06/Cargo.toml#L23

This hurts compile time for users because it forces their Cargo invocation to finish compiling miniserde before starting to compile miniserde-derive-enum, where otherwise they would be compiled in simultaneously on different cores.

Test-only dependencies should be under `[dev-dependencies]` and tests under a `tests` directory.
https://doc.rust-lang.org/rust-by-example/cargo/test.html

**Comment by eupn** [comment]
Got it, will remove prior to publishing.

**Comment by eupn** [comment]
Removed!
